#################################################
# FILENAME :        Makefile       
#
# DESCRIPTION :
# 		Makefile for Programming Assignment 1
#
# AUTHOR :    Joyce Huang (sh2393:Cornell University)        START DATE :    1 Feb 2019
#
# UPDATE :	 13 Feb 2019
#################################################


all: main

main: main.cpp
	g++ -o main main.cpp int_exception.cpp fp_exception.cpp helpers.cpp

pi: pi.cpp
	g++ -o pi pi.cpp

clean:
	rm -f main
	rm -f *.o